const cityStateLower: any = {
  "andaman and nicobar islands": ["port blair"],
  haryana: [
    "faridabad",
    "gurgaon",
    "hisar",
    "rohtak",
    "panipat",
    "karnal",
    "sonipat",
    "yamunanagar",
    "panchkula",
    "bhiwani",
    "bahadurgarh",
    "jind",
    "sirsa",
    "thanesar",
    "kaithal",
    "palwal",
    "rewari",
    "hansi",
    "narnaul",
    "fatehabad",
    "gohana",
    "tohana",
    "narwana",
    "mandi dabwali",
    "charkhi dadri",
    "shahbad",
    "pehowa",
    "samalkha",
    "pinjore",
    "ladwa",
    "sohna",
    "safidon",
    "taraori",
    "mahendragarh",
    "ratia",
    "rania",
    "sarsod",
  ],
  "tamil nadu": [
    "chennai",
    "coimbatore",
    "madurai",
    "tiruchirappalli",
    "salem",
    "tirunelveli",
    "tiruppur",
    "ranipet",
    "nagercoil",
    "thanjavur",
    "vellore",
    "kancheepuram",
    "erode",
    "tiruvannamalai",
    "pollachi",
    "rajapalayam",
    "sivakasi",
    "pudukkottai",
    "neyveli (ts)",
    "nagapattinam",
    "viluppuram",
    "tiruchengode",
    "vaniyambadi",
    "theni allinagaram",
    "udhagamandalam",
    "aruppukkottai",
    "paramakudi",
    "arakkonam",
    "virudhachalam",
    "srivilliputhur",
    "tindivanam",
    "virudhunagar",
    "karur",
    "valparai",
    "sankarankovil",
    "tenkasi",
    "palani",
    "pattukkottai",
    "tirupathur",
    "ramanathapuram",
    "udumalaipettai",
    "gobichettipalayam",
    "thiruvarur",
    "thiruvallur",
    "panruti",
    "namakkal",
    "thirumangalam",
    "vikramasingapuram",
    "nellikuppam",
    "rasipuram",
    "tiruttani",
    "nandivaram-guduvancheri",
    "periyakulam",
    "pernampattu",
    "vellakoil",
    "sivaganga",
    "vadalur",
    "rameshwaram",
    "tiruvethipuram",
    "perambalur",
    "usilampatti",
    "vedaranyam",
    "sathyamangalam",
    "puliyankudi",
    "nanjikottai",
    "thuraiyur",
    "sirkali",
    "tiruchendur",
    "periyasemur",
    "sattur",
    "vandavasi",
    "tharamangalam",
    "tirukkoyilur",
    "oddanchatram",
    "palladam",
    "vadakkuvalliyur",
    "tirukalukundram",
    "uthamapalayam",
    "surandai",
    "sankari",
    "shenkottai",
    "vadipatti",
    "sholingur",
    "tirupathur",
    "manachanallur",
    "viswanatham",
    "polur",
    "panagudi",
    "uthiramerur",
    "thiruthuraipoondi",
    "pallapatti",
    "ponneri",
    "lalgudi",
    "natham",
    "unnamalaikadai",
    "p.n.patti",
    "tharangambadi",
    "tittakudi",
    "pacode",
    "o' valley",
    "suriyampalayam",
    "sholavandan",
    "thammampatti",
    "namagiripettai",
    "peravurani",
    "parangipettai",
    "pudupattinam",
    "pallikonda",
    "sivagiri",
    "punjaipugalur",
    "padmanabhapuram",
    "thirupuvanam",
  ],
  "madhya pradesh": [
    "indore",
    "bhopal",
    "jabalpur",
    "gwalior",
    "ujjain",
    "sagar",
    "ratlam",
    "satna",
    "murwara (katni)",
    "morena",
    "singrauli",
    "rewa",
    "vidisha",
    "ganjbasoda",
    "shivpuri",
    "mandsaur",
    "neemuch",
    "nagda",
    "itarsi",
    "sarni",
    "sehore",
    "mhow cantonment",
    "seoni",
    "balaghat",
    "ashok nagar",
    "tikamgarh",
    "shahdol",
    "pithampur",
    "alirajpur",
    "mandla",
    "sheopur",
    "shajapur",
    "panna",
    "raghogarh-vijaypur",
    "sendhwa",
    "sidhi",
    "pipariya",
    "shujalpur",
    "sironj",
    "pandhurna",
    "nowgong",
    "mandideep",
    "sihora",
    "raisen",
    "lahar",
    "maihar",
    "sanawad",
    "sabalgarh",
    "umaria",
    "porsa",
    "narsinghgarh",
    "malaj khand",
    "sarangpur",
    "mundi",
    "nepanagar",
    "pasan",
    "mahidpur",
    "seoni-malwa",
    "rehli",
    "manawar",
    "rahatgarh",
    "panagar",
    "wara seoni",
    "tarana",
    "sausar",
    "rajgarh",
    "niwari",
    "mauganj",
    "manasa",
    "nainpur",
    "prithvipur",
    "sohagpur",
    "nowrozabad (khodargama)",
    "shamgarh",
    "maharajpur",
    "multai",
    "pali",
    "pachore",
    "rau",
    "mhowgaon",
    "vijaypur",
    "narsinghgarh",
  ],
  jharkhand: [
    "dhanbad",
    "ranchi",
    "jamshedpur",
    "bokaro steel city",
    "deoghar",
    "phusro",
    "adityapur",
    "hazaribag",
    "giridih",
    "ramgarh",
    "jhumri tilaiya",
    "saunda",
    "sahibganj",
    "medininagar (daltonganj)",
    "chaibasa",
    "chatra",
    "gumia",
    "dumka",
    "madhupur",
    "chirkunda",
    "pakaur",
    "simdega",
    "musabani",
    "mihijam",
    "patratu",
    "lohardaga",
    "tenu dam-cum-kathhara",
  ],
  mizoram: ["aizawl", "lunglei", "saiha"],
  nagaland: [
    "dimapur",
    "kohima",
    "zunheboto",
    "tuensang",
    "wokha",
    "mokokchung",
  ],
  "himachal pradesh": [
    "shimla",
    "mandi",
    "solan",
    "nahan",
    "sundarnagar",
    "palampur",
    "kullu",
  ],
  tripura: [
    "agartala",
    "udaipur",
    "dharmanagar",
    "pratapgarh",
    "kailasahar",
    "belonia",
    "khowai",
  ],
  "andhra pradesh": [
    "visakhapatnam",
    "vijayawada",
    "guntur",
    "nellore",
    "kurnool",
    "rajahmundry",
    "kakinada",
    "tirupati",
    "anantapur",
    "kadapa",
    "vizianagaram",
    "eluru",
    "ongole",
    "nandyal",
    "machilipatnam",
    "adoni",
    "tenali",
    "chittoor",
    "hindupur",
    "proddatur",
    "bhimavaram",
    "madanapalle",
    "guntakal",
    "dharmavaram",
    "gudivada",
    "srikakulam",
    "narasaraopet",
    "rajampet",
    "tadpatri",
    "tadepalligudem",
    "chilakaluripet",
    "yemmiganur",
    "kadiri",
    "chirala",
    "anakapalle",
    "kavali",
    "palacole",
    "sullurpeta",
    "tanuku",
    "rayachoti",
    "srikalahasti",
    "bapatla",
    "naidupet",
    "nagari",
    "gudur",
    "vinukonda",
    "narasapuram",
    "nuzvid",
    "markapur",
    "ponnur",
    "kandukur",
    "bobbili",
    "rayadurg",
    "samalkot",
    "jaggaiahpet",
    "tuni",
    "amalapuram",
    "bheemunipatnam",
    "venkatagiri",
    "sattenapalle",
    "pithapuram",
    "palasa kasibugga",
    "parvathipuram",
    "macherla",
    "gooty",
    "salur",
    "mandapeta",
    "jammalamadugu",
    "peddapuram",
    "punganur",
    "nidadavole",
    "repalle",
    "ramachandrapuram",
    "kovvur",
    "tiruvuru",
    "uravakonda",
    "narsipatnam",
    "yerraguntla",
    "pedana",
    "puttur",
    "renigunta",
    "rajam",
    "srisailam project (right flank colony) township",
  ],
  punjab: [
    "ludhiana",
    "patiala",
    "amritsar",
    "jalandhar",
    "bathinda",
    "pathankot",
    "hoshiarpur",
    "batala",
    "moga",
    "malerkotla",
    "khanna",
    "mohali",
    "barnala",
    "firozpur",
    "phagwara",
    "kapurthala",
    "zirakpur",
    "kot kapura",
    "faridkot",
    "muktsar",
    "rajpura",
    "sangrur",
    "fazilka",
    "gurdaspur",
    "kharar",
    "gobindgarh",
    "mansa",
    "malout",
    "nabha",
    "tarn taran",
    "jagraon",
    "sunam",
    "dhuri",
    "firozpur cantt.",
    "sirhind fatehgarh sahib",
    "rupnagar",
    "jalandhar cantt.",
    "samana",
    "nawanshahr",
    "rampura phul",
    "nangal",
    "nakodar",
    "zira",
    "patti",
    "raikot",
    "longowal",
    "urmar tanda",
    "morinda, india",
    "phillaur",
    "pattran",
    "qadian",
    "sujanpur",
    "mukerian",
    "talwara",
  ],
  chandigarh: ["chandigarh"],
  rajasthan: [
    "jaipur",
    "jodhpur",
    "bikaner",
    "udaipur",
    "ajmer",
    "bhilwara",
    "alwar",
    "bharatpur",
    "pali",
    "barmer",
    "sikar",
    "tonk",
    "sadulpur",
    "sawai madhopur",
    "nagaur",
    "makrana",
    "sujangarh",
    "sardarshahar",
    "ladnu",
    "ratangarh",
    "nokha",
    "nimbahera",
    "suratgarh",
    "rajsamand",
    "lachhmangarh",
    "rajgarh (churu)",
    "nasirabad",
    "nohar",
    "phalodi",
    "nathdwara",
    "pilani",
    "merta city",
    "sojat",
    "neem-ka-thana",
    "sirohi",
    "pratapgarh",
    "rawatbhata",
    "sangaria",
    "lalsot",
    "pilibanga",
    "pipar city",
    "taranagar",
    "vijainagar, ajmer",
    "sumerpur",
    "sagwara",
    "ramganj mandi",
    "lakheri",
    "udaipurwati",
    "losal",
    "sri madhopur",
    "ramngarh",
    "rawatsar",
    "rajakhera",
    "shahpura",
    "shahpura",
    "raisinghnagar",
    "malpura",
    "nadbai",
    "sanchore",
    "nagar",
    "rajgarh (alwar)",
    "sheoganj",
    "sadri",
    "todaraisingh",
    "todabhim",
    "reengus",
    "rajaldesar",
    "sadulshahar",
    "sambhar",
    "prantij",
    "mount abu",
    "mangrol",
    "phulera",
    "mandawa",
    "pindwara",
    "mandalgarh",
    "takhatgarh",
  ],
  assam: [
    "guwahati",
    "silchar",
    "dibrugarh",
    "nagaon",
    "tinsukia",
    "jorhat",
    "bongaigaon city",
    "dhubri",
    "diphu",
    "north lakhimpur",
    "tezpur",
    "karimganj",
    "sibsagar",
    "goalpara",
    "barpeta",
    "lanka",
    "lumding",
    "mankachar",
    "nalbari",
    "rangia",
    "margherita",
    "mangaldoi",
    "silapathar",
    "mariani",
    "marigaon",
  ],
  odisha: [
    "bhubaneswar",
    "cuttack",
    "raurkela",
    "brahmapur",
    "sambalpur",
    "puri",
    "baleshwar town",
    "baripada town",
    "bhadrak",
    "balangir",
    "jharsuguda",
    "bargarh",
    "paradip",
    "bhawanipatna",
    "dhenkanal",
    "barbil",
    "kendujhar",
    "sunabeda",
    "rayagada",
    "jatani",
    "byasanagar",
    "kendrapara",
    "rajagangapur",
    "parlakhemundi",
    "talcher",
    "sundargarh",
    "phulabani",
    "pattamundai",
    "titlagarh",
    "nabarangapur",
    "soro",
    "malkangiri",
    "rairangpur",
    "tarbha",
  ],
  chhattisgarh: [
    "raipur",
    "bhilai nagar",
    "korba",
    "bilaspur",
    "durg",
    "rajnandgaon",
    "jagdalpur",
    "raigarh",
    "ambikapur",
    "mahasamund",
    "dhamtari",
    "chirmiri",
    "bhatapara",
    "dalli-rajhara",
    "naila janjgir",
    "tilda newra",
    "mungeli",
    "manendragarh",
    "sakti",
  ],
  "jammu and kashmir": [
    "srinagar",
    "jammu",
    "baramula",
    "anantnag",
    "sopore",
    "kathurban agglomeration",
    "rajauri",
    "punch",
    "udhampur",
  ],
  karnataka: [
    "bengaluru",
    "hubli-dharwad",
    "belagavi",
    "mangaluru",
    "davanagere",
    "ballari",
    "mysore",
    "tumkur",
    "shivamogga",
    "raayachuru",
    "robertson pet",
    "kolar",
    "mandya",
    "udupi",
    "chikkamagaluru",
    "karwar",
    "ranebennuru",
    "ranibennur",
    "ramanagaram",
    "gokak",
    "yadgir",
    "rabkavi banhatti",
    "shahabad",
    "sirsi",
    "sindhnur",
    "tiptur",
    "arsikere",
    "nanjangud",
    "sagara",
    "sira",
    "puttur",
    "athni",
    "mulbagal",
    "surapura",
    "siruguppa",
    "mudhol",
    "sidlaghatta",
    "shahpur",
    "saundatti-yellamma",
    "wadi",
    "manvi",
    "nelamangala",
    "lakshmeshwar",
    "ramdurg",
    "nargund",
    "tarikere",
    "malavalli",
    "savanur",
    "lingsugur",
    "vijayapura",
    "sankeshwara",
    "madikeri",
    "talikota",
    "sedam",
    "shikaripur",
    "mahalingapura",
    "mudalagi",
    "muddebihal",
    "pavagada",
    "malur",
    "sindhagi",
    "sanduru",
    "afzalpur",
    "maddur",
    "madhugiri",
    "tekkalakote",
    "terdal",
    "mudabidri",
    "magadi",
    "navalgund",
    "shiggaon",
    "shrirangapattana",
    "sindagi",
    "sakaleshapura",
    "srinivaspur",
    "ron",
    "mundargi",
    "sadalagi",
    "piriyapatna",
    "adyar",
  ],
  manipur: ["imphal", "thoubal", "lilong", "mayang imphal"],
  kerala: [
    "thiruvananthapuram",
    "kochi",
    "kozhikode",
    "kollam",
    "thrissur",
    "palakkad",
    "alappuzha",
    "malappuram",
    "ponnani",
    "vatakara",
    "kanhangad",
    "taliparamba",
    "koyilandy",
    "neyyattinkara",
    "kayamkulam",
    "nedumangad",
    "kannur",
    "tirur",
    "kottayam",
    "kasaragod",
    "kunnamkulam",
    "ottappalam",
    "thiruvalla",
    "thodupuzha",
    "chalakudy",
    "changanassery",
    "punalur",
    "nilambur",
    "cherthala",
    "perinthalmanna",
    "mattannur",
    "shoranur",
    "varkala",
    "paravoor",
    "pathanamthitta",
    "peringathur",
    "attingal",
    "kodungallur",
    "pappinisseri",
    "chittur-thathamangalam",
    "muvattupuzha",
    "adoor",
    "mavelikkara",
    "mavoor",
    "perumbavoor",
    "vaikom",
    "palai",
    "panniyannur",
    "guruvayoor",
    "puthuppally",
    "panamattom",
  ],
  delhi: ["delhi", "new delhi"],
  "dadra and nagar haveli": ["silvassa"],
  puducherry: ["pondicherry", "karaikal", "yanam", "mahe"],
  uttarakhand: [
    "dehradun",
    "hardwar",
    "haldwani-cum-kathgodam",
    "srinagar",
    "kashipur",
    "roorkee",
    "rudrapur",
    "rishikesh",
    "ramnagar",
    "pithoragarh",
    "manglaur",
    "nainital",
    "mussoorie",
    "tehri",
    "pauri",
    "nagla",
    "sitarganj",
    "bageshwar",
  ],
  "uttar pradesh": [
    "lucknow",
    "kanpur",
    "firozabad",
    "agra",
    "meerut",
    "varanasi",
    "allahabad",
    "amroha",
    "moradabad",
    "aligarh",
    "saharanpur",
    "noida",
    "loni",
    "jhansi",
    "shahjahanpur",
    "rampur",
    "modinagar",
    "hapur",
    "etawah",
    "sambhal",
    "orai",
    "bahraich",
    "unnao",
    "rae bareli",
    "lakhimpur",
    "sitapur",
    "lalitpur",
    "pilibhit",
    "chandausi",
    "hardoi ",
    "azamgarh",
    "khair",
    "sultanpur",
    "tanda",
    "nagina",
    "shamli",
    "najibabad",
    "shikohabad",
    "sikandrabad",
    "shahabad, hardoi",
    "pilkhuwa",
    "renukoot",
    "vrindavan",
    "ujhani",
    "laharpur",
    "tilhar",
    "sahaswan",
    "rath",
    "sherkot",
    "kalpi",
    "tundla",
    "sandila",
    "nanpara",
    "sardhana",
    "nehtaur",
    "seohara",
    "padrauna",
    "mathura",
    "thakurdwara",
    "nawabganj",
    "siana",
    "noorpur",
    "sikandra rao",
    "puranpur",
    "rudauli",
    "thana bhawan",
    "palia kalan",
    "zaidpur",
    "nautanwa",
    "zamania",
    "shikarpur, bulandshahr",
    "naugawan sadat",
    "fatehpur sikri",
    "shahabad, rampur",
    "robertsganj",
    "utraula",
    "sadabad",
    "rasra",
    "lar",
    "lal gopalganj nindaura",
    "sirsaganj",
    "pihani",
    "shamsabad, agra",
    "rudrapur",
    "soron",
    "surban agglomerationr",
    "samdhan",
    "sahjanwa",
    "rampur maniharan",
    "sumerpur",
    "shahganj",
    "tulsipur",
    "tirwaganj",
    "purqurban agglomerationzi",
    "shamsabad, farrukhabad",
    "warhapur",
    "powayan",
    "sandi",
    "achhnera",
    "naraura",
    "nakur",
    "sahaspur",
    "safipur",
    "reoti",
    "sikanderpur",
    "saidpur",
    "sirsi",
    "purwa",
    "parasi",
    "lalganj",
    "phulpur",
    "shishgarh",
    "sahawar",
    "samthar",
    "pukhrayan",
    "obra",
    "niwai",
    "mirzapur",
  ],
  bihar: [
    "patna",
    "gaya",
    "bhagalpur",
    "muzaffarpur",
    "darbhanga",
    "arrah",
    "begusarai",
    "chhapra",
    "katihar",
    "munger",
    "purnia",
    "saharsa",
    "sasaram",
    "hajipur",
    "dehri-on-sone",
    "bettiah",
    "motihari",
    "bagaha",
    "siwan",
    "kishanganj",
    "jamalpur",
    "buxar",
    "jehanabad",
    "aurangabad",
    "lakhisarai",
    "nawada",
    "jamui",
    "sitamarhi",
    "araria",
    "gopalganj",
    "madhubani",
    "masaurhi",
    "samastipur",
    "mokameh",
    "supaul",
    "dumraon",
    "arwal",
    "forbesganj",
    "bhaburban agglomeration",
    "narkatiaganj",
    "naugachhia",
    "madhepura",
    "sheikhpura",
    "sultanganj",
    "raxaul bazar",
    "ramnagar",
    "mahnar bazar",
    "warisaliganj",
    "revelganj",
    "rajgir",
    "sonepur",
    "sherghati",
    "sugauli",
    "makhdumpur",
    "maner",
    "rosera",
    "nokha",
    "piro",
    "rafiganj",
    "marhaura",
    "mirganj",
    "lalganj",
    "murliganj",
    "motipur",
    "manihari",
    "sheohar",
    "maharajganj",
    "silao",
    "barh",
    "asarganj",
  ],
  gujarat: [
    "ahmedabad",
    "surat",
    "vadodara",
    "rajkot",
    "bhavnagar",
    "jamnagar",
    "nadiad",
    "porbandar",
    "anand",
    "morvi",
    "mahesana",
    "bharuch",
    "vapi",
    "navsari",
    "veraval",
    "bhuj",
    "godhra",
    "palanpur",
    "valsad",
    "patan",
    "deesa",
    "amreli",
    "anjar",
    "dhoraji",
    "khambhat",
    "mahuva",
    "keshod",
    "wadhwan",
    "ankleshwar",
    "savarkundla",
    "kadi",
    "visnagar",
    "upleta",
    "una",
    "sidhpur",
    "unjha",
    "mangrol",
    "viramgam",
    "modasa",
    "palitana",
    "petlad",
    "kapadvanj",
    "sihor",
    "wankaner",
    "limbdi",
    "mandvi",
    "thangadh",
    "vyara",
    "padra",
    "lunawada",
    "rajpipla",
    "vapi",
    "umreth",
    "sanand",
    "rajula",
    "radhanpur",
    "mahemdabad",
    "ranavav",
    "tharad",
    "mansa",
    "umbergaon",
    "talaja",
    "vadnagar",
    "manavadar",
    "salaya",
    "vijapur",
    "pardi",
    "rapar",
    "songadh",
    "lathi",
    "adalaj",
    "chhapra",
    "gandhinagar",
  ],
  telangana: [
    "hyderabad",
    "warangal",
    "nizamabad",
    "karimnagar",
    "ramagundam",
    "khammam",
    "mahbubnagar",
    "mancherial",
    "adilabad",
    "suryapet",
    "jagtial",
    "miryalaguda",
    "nirmal",
    "kamareddy",
    "kothagudem",
    "bodhan",
    "palwancha",
    "mandamarri",
    "koratla",
    "sircilla",
    "tandur",
    "siddipet",
    "wanaparthy",
    "kagaznagar",
    "gadwal",
    "sangareddy",
    "bellampalle",
    "bhongir",
    "vikarabad",
    "jangaon",
    "bhadrachalam",
    "bhainsa",
    "farooqnagar",
    "medak",
    "narayanpet",
    "sadasivpet",
    "yellandu",
    "manuguru",
    "kyathampalle",
    "nagarkurnool",
  ],
  meghalaya: ["shillong", "tura", "nongstoin"],
  "himachal praddesh": ["manali"],
  "arunachal pradesh": ["naharlagun", "pasighat"],
  maharashtra: [
    "mumbai",
    "pune",
    "nagpur",
    "thane",
    "nashik",
    "kalyan-dombivali",
    "vasai-virar",
    "solapur",
    "mira-bhayandar",
    "bhiwandi",
    "amravati",
    "nanded-waghala",
    "sangli",
    "malegaon",
    "akola",
    "latur",
    "dhule",
    "ahmednagar",
    "ichalkaranji",
    "parbhani",
    "panvel",
    "yavatmal",
    "achalpur",
    "osmanabad",
    "nandurbar",
    "satara",
    "wardha",
    "udgir",
    "aurangabad",
    "amalner",
    "akot",
    "pandharpur",
    "shrirampur",
    "parli",
    "washim",
    "ambejogai",
    "manmad",
    "ratnagiri",
    "uran islampur",
    "pusad",
    "sangamner",
    "shirpur-warwade",
    "malkapur",
    "wani",
    "lonavla",
    "talegaon dabhade",
    "anjangaon",
    "umred",
    "palghar",
    "shegaon",
    "ozar",
    "phaltan",
    "yevla",
    "shahade",
    "vita",
    "umarkhed",
    "warora",
    "pachora",
    "tumsar",
    "manjlegaon",
    "sillod",
    "arvi",
    "nandura",
    "vaijapur",
    "wadgaon road",
    "sailu",
    "murtijapur",
    "tasgaon",
    "mehkar",
    "yawal",
    "pulgaon",
    "nilanga",
    "wai",
    "umarga",
    "paithan",
    "rahuri",
    "nawapur",
    "tuljapur",
    "morshi",
    "purna",
    "satana",
    "pathri",
    "sinnar",
    "uchgaon",
    "uran",
    "pen",
    "karjat",
    "manwath",
    "partur",
    "sangole",
    "mangrulpir",
    "risod",
    "shirur",
    "savner",
    "sasvad",
    "pandharkaoda",
    "talode",
    "shrigonda",
    "shirdi",
    "raver",
    "mukhed",
    "rajura",
    "vadgaon kasba",
    "tirora",
    "mahad",
    "lonar",
    "sawantwadi",
    "pathardi",
    "pauni",
    "ramtek",
    "mul",
    "soyagaon",
    "mangalvedhe",
    "narkhed",
    "shendurjana",
    "patur",
    "mhaswad",
    "loha",
    "nandgaon",
    "warud",
  ],
  goa: ["marmagao", "panaji", "margao", "mapusa"],
  "west bengal": [
    "kolkata",
    "siliguri",
    "asansol",
    "raghunathganj",
    "kharagpur",
    "naihati",
    "english bazar",
    "baharampur",
    "hugli-chinsurah",
    "raiganj",
    "jalpaiguri",
    "santipur",
    "balurghat",
    "medinipur",
    "habra",
    "ranaghat",
    "bankura",
    "nabadwip",
    "darjiling",
    "purulia",
    "arambagh",
    "tamluk",
    "alipurdurban agglomerationr",
    "suri",
    "jhargram",
    "gangarampur",
    "rampurhat",
    "kalimpong",
    "sainthia",
    "taki",
    "murshidabad",
    "memari",
    "paschim punropara",
    "tarakeswar",
    "sonamukhi",
    "pandurban agglomeration",
    "mainaguri",
    "malda",
    "panchla",
    "raghunathpur",
    "mathabhanga",
    "monoharpur",
    "srirampore",
    "adra",
  ],
};

const stateArray = [
  "andaman and nicobar islands",
  "haryana",
  "tamil nadu",
  "madhya pradesh",
  "jharkhand",
  "mizoram",
  "nagaland",
  "himachal pradesh",
  "tripura",
  "andhra pradesh",
  "punjab",
  "chandigarh",
  "rajasthan",
  "assam",
  "odisha",
  "chhattisgarh",
  "jammu and kashmir",
  "karnataka",
  "manipur",
  "kerala",
  "delhi",
  "dadra and nagar haveli",
  "puducherry",
  "uttarakhand",
  "uttar pradesh",
  "bihar",
  "gujarat",
  "telangana",
  "meghalaya",
  "himachal praddesh",
  "arunachal pradesh",
  "maharashtra",
  "goa",
  "west bengal",
];

export function concatLandmark(address: string, landmark: string) {
  const addressLowerCase = address.toLowerCase();
  const addressParts: any = {
    city: "",
    state: "",
    pincode: "",
  };

  const split = addressLowerCase.split(",");

  for (let i = 0; i < split.length; i++) {
    split[i] = split[i].trim();
  }

  for (let i = 0; i < split.length; i++) {
    if (stateArray.includes(split[i])) {
      addressParts.state = split[i];
    }
    if (
      addressParts.state &&
      cityStateLower[addressParts.state].includes(split[i])
    ) {
      addressParts.city = split[i];
    }

    if (Number(split[i])) {
      addressParts.pincode = split[i];
    }
  }

  if (addressParts.state) {
    for (let i = 0; i < split.length; i++) {
      if (cityStateLower[addressParts.state].includes(split[i])) {
        addressParts.city = split[i];
      }
    }
  }

  const strIndex = addressLowerCase.indexOf(split[split.length - 3]);
  const newAddress = `${address.slice(
    0,
    strIndex
  )} near ${landmark}, ${address.slice(strIndex, address.length)}`;
  return newAddress;
}

export function percentile(data: any) {
  const max: any = data[0];
  const array: Array<Number> = [];
  for (let i = 0; i < data.length; i++) {
    const percentage = Math.round((data[i] / max) * 100);
    array.push(percentage);
  }
  return array;
}
